name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go version

      - name: Pull in all Go dependencies
        run: |
          go mod vendor

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Check that go modules are in synced state
        run: |
          go mod tidy -v
          if [ -n "$(git status --porcelain go.mod go.sum)" ]; then
            echo "Go modules are dirty or not in a good state. Please run go mod tidy"
            exit 1;
          fi

      - name: run tests
        run: |
          make test
